### ISSUE TITLE
Both edit and reading mode having the same background color

### ISSUE THREAD

**Issue by izzatz** [rfaccio/dracula-abap#1]
I'm not sure is as per design? I would prefer to have two different sets of colors to determine whether I'm in edit or read mode.

**Comment by rfaccio** [comment]
I agree with you, in this first version I was having trouble finding a pleasing combination between background colors in edit mode and read mode using the dracula proposed colors without compromising contrast and readabilty.


The ABAP Theme Editor is very limited, so 2 background colors must work with the same colors for all the other symbols.


I've played around a bit and settled with this: a 10% darker hex code #111217 while in edit mode (for contrast); the regular dracula proposed brackground #282a36 for read mode.

Let me know what you think and I will update the files as soon as possible:

Edit mode:
![image](https://user-images.githubusercontent.com/183634/116444695-61096d80-a82b-11eb-99d2-549d8ea47ecb.png)

Read mode:
![image](https://user-images.githubusercontent.com/183634/116444774-77172e00-a82b-11eb-8c8f-0d1c4ad177c2.png)

**Comment by izzatz** [comment]
Hi @rfaccio 

Yes, this is fine with me.  

Maybe you could put up a comment on the background line, so people can manually change it base on their liking. 

Thanks!

**Comment by rfaccio** [comment]
Thank you for the feedback @izzatz!

I've updated the file and added a new section to the INSTALL.md file, with instructions on how to customize xml tags using internal SAP color codes.
