### ISSUE TITLE
Not working on SAP GUI 7.5

### ISSUE THREAD

**Issue by freyesdrs6** [rfaccio/dracula-abap#3]
I did the steps indicated, but the editor did not change.
![2021-05-01 10_37_53-ab4_data](https://user-images.githubusercontent.com/77644483/116788898-66ec9200-aa69-11eb-80f9-0f7153157811.png)

![2021-05-01 10_38_52-Editor ABAP_ Report ZTEXTSSS Modificar](https://user-images.githubusercontent.com/77644483/116788916-77047180-aa69-11eb-8e67-c48fdde8e54e.png)

Any ideas why it doesn't work?

Greetings

**Comment by rfaccio** [comment]
Hi @freyesdrs6 !

It looks like the file path in your image is the incorrect one. 

Try using `Windows Key+ R`, and pasting `%APPDATA%\SAP\SAP GUI\ABAP Editor\` to access the correct one.
It should be under the `AppData\Roaming`... subfolders, not `Program Files`.
Remeber to also close all instances of the SAP GUI as well.

Hope it works this time.

**Comment by freyesdrs6** [comment]
> Hi @freyesdrs6 !
> 
> It looks like the file path in your image is the incorrect one.
> 
> Try using `Windows Key+ R`, and pasting `%APPDATA%\SAP\SAP GUI\ABAP Editor\` to access the correct one.
> It should be under the `AppData\Roaming`... subfolders, not `Program Files`.
> Remeber to also close all instances of the SAP GUI as well.
> 
> Hope it works this time.

Hi @rfaccio 

You are absolutely right, the route was wrong and I did not verify it. It already works and is perfect. Thanks for your help.

![2021-05-03 09_19_43-Editor ABAP_ Report ZFI_PRG_CONTABILIZA_CXP_2 Modificar](https://user-images.githubusercontent.com/77644483/116895785-c88b3880-abf0-11eb-9d49-555018853e25.png)

Greetings

**Comment by rfaccio** [comment]
I'm glad it worked!
